### ISSUE TITLE
Review 1a15. need some notes on our indepedent variables

### ISSUE THREAD

**Issue by timm** [timm/TSE_StaticCode_Singapore-2022#2]
Need a table, maybe 14 to 13rd of page, maybe full width describing the inputs to these models. 

In the section 5.1 (data).

**Comment by timm** [comment]
Also, @kanghj , we have some 250 variables used as inputs to this while process. is there some way to group them? succinctly describe NOT each one but some sort of characterization over similar ones?

**Comment by kanghj** [comment]
<img width="720" alt="Screenshot 2022-09-30 at 5 54 01 PM" src="https://user-images.githubusercontent.com/2216119/193244859-4d4080f6-806f-4c3c-8d6f-d94ab89b44ca.png">

added a table along with descriptions of the feature categories

**Comment by yrahul3910** [comment]
Marking as closed. There is now text in the paper and a reference to that text in the response.

**Comment by timm** [comment]
thank you @kanghj ! nice job!
